# Generated by Django 6.0.5 on 2026-05-17 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenzia',
            fields=[
                ('id_agenzia', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('partita_iva', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('indirizzo_sede', models.CharField(blank=True, max_length=255, null=True)),
                ('descrizione', models.TextField(blank=True, db_column='Descrizione', null=True)),
            ],
            options={
                'db_table': 'agenzia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Alloggio',
            fields=[
                ('id_alloggio', models.AutoField(primary_key=True, serialize=False)),
                ('titolo', models.CharField(max_length=255)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('indirizzo', models.CharField(blank=True, max_length=255, null=True)),
                ('prezzo_notte', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('capienza', models.IntegerField(blank=True, null=True)),
                ('tipo_alloggio', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_camere', models.IntegerField(blank=True, null=True)),
                ('numero_letti', models.IntegerField(blank=True, null=True)),
                ('numero_bagni', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alloggio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id_badge', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descrizione', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'badge',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Citta',
            fields=[
                ('id_citta', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('nazione', models.CharField(max_length=255)),
                ('regione', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'citta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Esperienze',
            fields=[
                ('id_esperienza', models.AutoField(primary_key=True, serialize=False)),
                ('titolo', models.CharField(max_length=255)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('prezzo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('durata', models.CharField(blank=True, max_length=50, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('capienza_massima', models.IntegerField(blank=True, null=True)),
                ('luogo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'esperienze',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id_utente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cognome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('data_registrazione', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'utente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lingua',
            fields=[
                ('id_lingua', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'lingua',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('pk', models.CompositePrimaryKey('id_alloggio', 'id_servizio', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'offre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ottiene',
            fields=[
                ('pk', models.CompositePrimaryKey('id_host', 'id_badge', blank=True, editable=False, primary_key=True, serialize=False)),
                ('data_ottenimento', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ottiene',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParlaAgenzia',
            fields=[
                ('pk', models.CompositePrimaryKey('id_agenzia', 'id_lingua', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'parla_agenzia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParlaHost',
            fields=[
                ('pk', models.CompositePrimaryKey('id_host', 'id_lingua', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'parla_host',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrenotazioneAlloggio',
            fields=[
                ('id_prenotazione', models.AutoField(primary_key=True, serialize=False)),
                ('data_prenotazione', models.DateField(blank=True, null=True)),
                ('check_in', models.DateField(blank=True, null=True)),
                ('check_out', models.DateField(blank=True, null=True)),
                ('numero_ospiti', models.IntegerField(blank=True, null=True)),
                ('prezzo_totale', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stato', models.CharField(blank=True, max_length=50, null=True)),
                ('codice_conferma', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'prenotazione_alloggio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrenotazioneEsperienze',
            fields=[
                ('id_prenotazione_esperienza', models.AutoField(primary_key=True, serialize=False)),
                ('data_prenotazione', models.DateField(blank=True, null=True)),
                ('data_esperienza', models.DateField(blank=True, null=True)),
                ('numero_partecipanti', models.IntegerField(blank=True, null=True)),
                ('prezzo_totale', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stato', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'prenotazione_esperienze',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PuntiInteresse',
            fields=[
                ('id_punto_interesse', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'punti_interesse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecensioneAlloggio',
            fields=[
                ('id_recensione', models.AutoField(primary_key=True, serialize=False)),
                ('voto', models.IntegerField(blank=True, null=True)),
                ('commento', models.TextField(blank=True, null=True)),
                ('data_recensione', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recensione_alloggio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecensioneEsperienze',
            fields=[
                ('id_recensione_esperienza', models.AutoField(primary_key=True, serialize=False)),
                ('voto', models.IntegerField(blank=True, null=True)),
                ('commento', models.TextField(blank=True, null=True)),
                ('data_recensione', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recensione_esperienze',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servizio',
            fields=[
                ('id_servizio', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'servizio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaAlloggiConServizi',
            fields=[
                ('id_alloggio', models.IntegerField(primary_key=True, serialize=False)),
                ('titolo', models.CharField(max_length=255)),
                ('prezzo_notte', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo_alloggio', models.CharField(blank=True, max_length=100, null=True)),
                ('id_citta', models.IntegerField(blank=True, null=True)),
                ('servizi_offerti', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vista_alloggi_con_servizi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaClassificaAlloggi',
            fields=[
                ('id_alloggio', models.IntegerField(primary_key=True, serialize=False)),
                ('titolo', models.CharField(max_length=255)),
                ('tipo_alloggio', models.CharField(blank=True, max_length=100, null=True)),
                ('citta', models.CharField(max_length=255)),
                ('media_voti', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True)),
                ('numero_recensioni', models.BigIntegerField()),
            ],
            options={
                'db_table': 'vista_classifica_alloggi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaClassificaEsperienze',
            fields=[
                ('id_esperienza', models.IntegerField(primary_key=True, serialize=False)),
                ('titolo', models.CharField(max_length=255)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('media_voti', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True)),
                ('numero_recensioni', models.BigIntegerField()),
            ],
            options={
                'db_table': 'vista_classifica_esperienze',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaDashboardGuadagniAgenzia',
            fields=[
                ('id_agenzia', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_agenzia', models.CharField(max_length=255)),
                ('numero_prenotazioni_totali', models.BigIntegerField()),
                ('totale_guadagnato_euro', models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True)),
                ('totale_partecipanti', models.DecimalField(blank=True, decimal_places=0, max_digits=32, null=True)),
            ],
            options={
                'db_table': 'vista_dashboard_guadagni_agenzia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaDashboardGuadagniHost',
            fields=[
                ('id_host', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cognome', models.CharField(max_length=255)),
                ('numero_prenotazioni_totali', models.BigIntegerField()),
                ('totale_guadagnato_euro', models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True)),
            ],
            options={
                'db_table': 'vista_dashboard_guadagni_host',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaDettaglioPrenotazioneOspite',
            fields=[
                ('id_prenotazione', models.IntegerField(primary_key=True, serialize=False)),
                ('ospite_id', models.IntegerField(blank=True, null=True)),
                ('nome_alloggio', models.CharField(max_length=255)),
                ('citta_alloggio', models.CharField(max_length=255)),
                ('check_in', models.DateField(blank=True, null=True)),
                ('check_out', models.DateField(blank=True, null=True)),
                ('prezzo_totale', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stato', models.CharField(blank=True, max_length=50, null=True)),
                ('codice_conferma', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_host', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'vista_dettaglio_prenotazione_ospite',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaEsploraDintorni',
            fields=[
                ('id_alloggio', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_alloggio', models.CharField(max_length=255)),
                ('citta', models.CharField(max_length=255)),
                ('punto_interesse', models.CharField(max_length=255)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('descrizione', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vista_esplora_dintorni',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaFatturazionePrenotazioni',
            fields=[
                ('id_prenotazione', models.IntegerField(primary_key=True, serialize=False)),
                ('codice_conferma', models.CharField(blank=True, max_length=100, null=True)),
                ('data_prenotazione', models.DateField(blank=True, null=True)),
                ('nome_ospite', models.CharField(max_length=255)),
                ('cognome_ospite', models.CharField(max_length=255)),
                ('alloggio_prenotato', models.CharField(max_length=255)),
                ('nome_host_proprietario', models.CharField(max_length=255)),
                ('cognome_host_proprietario', models.CharField(max_length=255)),
                ('prezzo_totale', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'vista_fatturazione_prenotazioni',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaPrenotazioniDaRecensire',
            fields=[
                ('id_prenotazione', models.IntegerField(primary_key=True, serialize=False)),
                ('codice_conferma', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_ospite', models.CharField(max_length=255)),
                ('email_ospite', models.CharField(max_length=255)),
                ('nome_alloggio', models.CharField(max_length=255)),
                ('check_out', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vista_prenotazioni_da_recensire',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaProfiloAgenziaCompleto',
            fields=[
                ('id_agenzia', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('lingue_parlate', models.TextField(blank=True, null=True)),
                ('numero_esperienze_offerte', models.BigIntegerField()),
            ],
            options={
                'db_table': 'vista_profilo_agenzia_completo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaProfiloHostCompleto',
            fields=[
                ('id_utente', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cognome', models.CharField(max_length=255)),
                ('descrizione_profilo', models.TextField(blank=True, null=True)),
                ('data_attivazione', models.DateField(blank=True, null=True)),
                ('lingue_parlate', models.TextField(blank=True, null=True)),
                ('badge_ottenuti', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vista_profilo_host_completo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaProfiloOspiteCrm',
            fields=[
                ('id_utente', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cognome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('soggiorni_effettuati', models.BigIntegerField()),
                ('esperienze_svolte', models.BigIntegerField()),
            ],
            options={
                'db_table': 'vista_profilo_ospite_crm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaStatisticheServizi',
            fields=[
                ('id_servizio', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_servizio', models.CharField(max_length=255)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_alloggi_che_lo_offrono', models.BigIntegerField()),
            ],
            options={
                'db_table': 'vista_statistiche_servizi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaTopDestinazioni',
            fields=[
                ('id_citta', models.IntegerField(primary_key=True, serialize=False)),
                ('citta', models.CharField(max_length=255)),
                ('nazione', models.CharField(max_length=255)),
                ('numero_alloggi_disponibili', models.BigIntegerField()),
                ('numero_prenotazioni_totali', models.BigIntegerField()),
            ],
            options={
                'db_table': 'vista_top_destinazioni',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id_host', models.OneToOneField(db_column='id_host', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.utente')),
                ('descrizione_profilo', models.TextField(blank=True, null=True)),
                ('data_attivazione', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'host',
                'managed': False,
            },
        ),
    ]
